/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  boolean,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_users_role = pgEnum("enum_users_role", [
  "admin",
  "editor",
  "contributor",
]);
export const enum_registrations_dietary_restrictions = pgEnum(
  "enum_registrations_dietary_restrictions",
  ["none", "vegetarian", "vegan", "halal", "gluten-free", "other"],
);
export const enum_registrations_category = pgEnum(
  "enum_registrations_category",
  ["student", "researcher", "policymaker", "partner", "observer"],
);
export const enum_registrations_tshirt_size = pgEnum(
  "enum_registrations_tshirt_size",
  ["xs", "s", "m", "l", "xl", "xxl"],
);
export const enum_registrations_status = pgEnum("enum_registrations_status", [
  "pending",
  "confirmed",
  "cancelled",
]);
export const enum_registrations_payment_status = pgEnum(
  "enum_registrations_payment_status",
  ["pending", "paid", "waived"],
);
export const enum_abstracts_track = pgEnum("enum_abstracts_track", [
  "srhr",
  "education",
  "advocacy",
  "innovation",
]);
export const enum_abstracts_presentation_type = pgEnum(
  "enum_abstracts_presentation_type",
  ["oral", "poster", "either"],
);
export const enum_abstracts_status = pgEnum("enum_abstracts_status", [
  "received",
  "under-review",
  "revisions",
  "accepted",
  "rejected",
]);
export const enum_speakers_type = pgEnum("enum_speakers_type", [
  "keynote",
  "plenary",
  "moderator",
  "facilitator",
  "presenter",
]);
export const enum_sessions_type = pgEnum("enum_sessions_type", [
  "keynote",
  "plenary",
  "panel",
  "workshop",
  "oral",
  "poster",
  "networking",
  "side-event",
]);
export const enum_sessions_track = pgEnum("enum_sessions_track", [
  "srhr",
  "education",
  "advocacy",
  "innovation",
  "general",
]);
export const enum_resources_topics = pgEnum("enum_resources_topics", [
  "srh",
  "education",
  "advocacy",
  "policy",
  "innovation",
  "empowerment",
  "gender",
  "hiv",
  "research",
]);
export const enum_resources_type = pgEnum("enum_resources_type", [
  "report",
  "paper",
  "brief",
  "presentation",
  "toolkit",
  "infographic",
  "video",
  "other",
]);
export const enum_resources_sarsyc_edition = pgEnum(
  "enum_resources_sarsyc_edition",
  ["1", "2", "3", "4", "5", "6", "other"],
);
export const enum_resources_language = pgEnum("enum_resources_language", [
  "en",
  "fr",
  "pt",
]);
export const enum_news_category = pgEnum("enum_news_category", [
  "conference",
  "speakers",
  "partnerships",
  "youth-stories",
  "research",
  "advocacy",
  "events",
]);
export const enum_news_status = pgEnum("enum_news_status", [
  "draft",
  "published",
  "archived",
]);
export const enum_partners_sarsyc_editions = pgEnum(
  "enum_partners_sarsyc_editions",
  ["1", "2", "3", "4", "5", "6"],
);
export const enum_partners_type = pgEnum("enum_partners_type", [
  "implementing",
  "funding",
  "technical",
  "media",
  "sponsor",
]);
export const enum_partners_tier = pgEnum("enum_partners_tier", [
  "platinum",
  "gold",
  "silver",
  "bronze",
  "in-kind",
  "n/a",
]);
export const enum_faqs_category = pgEnum("enum_faqs_category", [
  "general",
  "registration",
  "abstracts",
  "travel",
  "visa",
  "programme",
  "accessibility",
  "partnerships",
]);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    firstName: varchar("first_name").notNull(),
    lastName: varchar("last_name").notNull(),
    role: enum_users_role("role").notNull().default("editor"),
    organization: varchar("organization"),
    phone: varchar("phone"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const registrations_dietary_restrictions = pgTable(
  "registrations_dietary_restrictions",
  {
    order: integer("order").notNull(),
    parent: integer("parent_id").notNull(),
    value: enum_registrations_dietary_restrictions("value"),
    id: serial("id").primaryKey(),
  },
  (columns) => [
    index("registrations_dietary_restrictions_order_idx").on(columns.order),
    index("registrations_dietary_restrictions_parent_idx").on(columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [registrations.id],
      name: "registrations_dietary_restrictions_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const registrations = pgTable(
  "registrations",
  {
    id: serial("id").primaryKey(),
    firstName: varchar("first_name").notNull(),
    lastName: varchar("last_name").notNull(),
    email: varchar("email").notNull(),
    phone: varchar("phone").notNull(),
    country: varchar("country").notNull(),
    organization: varchar("organization").notNull(),
    category: enum_registrations_category("category").notNull(),
    accessibilityNeeds: varchar("accessibility_needs"),
    tshirtSize: enum_registrations_tshirt_size("tshirt_size"),
    registrationId: varchar("registration_id"),
    status: enum_registrations_status("status").notNull().default("pending"),
    paymentStatus:
      enum_registrations_payment_status("payment_status").default("pending"),
    notes: varchar("notes"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("registrations_email_idx").on(columns.email),
    uniqueIndex("registrations_registration_id_idx").on(columns.registrationId),
    index("registrations_updated_at_idx").on(columns.updatedAt),
    index("registrations_created_at_idx").on(columns.createdAt),
  ],
);

export const abstracts_keywords = pgTable(
  "abstracts_keywords",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    keyword: varchar("keyword"),
  },
  (columns) => [
    index("abstracts_keywords_order_idx").on(columns._order),
    index("abstracts_keywords_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [abstracts.id],
      name: "abstracts_keywords_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const abstracts_co_authors = pgTable(
  "abstracts_co_authors",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    name: varchar("name").notNull(),
    organization: varchar("organization"),
  },
  (columns) => [
    index("abstracts_co_authors_order_idx").on(columns._order),
    index("abstracts_co_authors_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [abstracts.id],
      name: "abstracts_co_authors_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const abstracts = pgTable(
  "abstracts",
  {
    id: serial("id").primaryKey(),
    submissionId: varchar("submission_id"),
    title: varchar("title").notNull(),
    abstract: varchar("abstract").notNull(),
    track: enum_abstracts_track("track").notNull(),
    primaryAuthor_firstName: varchar("primary_author_first_name").notNull(),
    primaryAuthor_lastName: varchar("primary_author_last_name").notNull(),
    primaryAuthor_email: varchar("primary_author_email").notNull(),
    primaryAuthor_phone: varchar("primary_author_phone"),
    primaryAuthor_organization: varchar(
      "primary_author_organization",
    ).notNull(),
    primaryAuthor_country: varchar("primary_author_country").notNull(),
    abstractFile: integer("abstract_file_id").references(() => media.id, {
      onDelete: "set null",
    }),
    presentationType: enum_abstracts_presentation_type("presentation_type"),
    status: enum_abstracts_status("status").notNull().default("received"),
    reviewerComments: varchar("reviewer_comments"),
    assignedSession: integer("assigned_session_id").references(
      () => sessions.id,
      {
        onDelete: "set null",
      },
    ),
    adminNotes: varchar("admin_notes"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("abstracts_submission_id_idx").on(columns.submissionId),
    index("abstracts_abstract_file_idx").on(columns.abstractFile),
    index("abstracts_assigned_session_idx").on(columns.assignedSession),
    index("abstracts_updated_at_idx").on(columns.updatedAt),
    index("abstracts_created_at_idx").on(columns.createdAt),
  ],
);

export const speakers_type = pgTable(
  "speakers_type",
  {
    order: integer("order").notNull(),
    parent: integer("parent_id").notNull(),
    value: enum_speakers_type("value"),
    id: serial("id").primaryKey(),
  },
  (columns) => [
    index("speakers_type_order_idx").on(columns.order),
    index("speakers_type_parent_idx").on(columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [speakers.id],
      name: "speakers_type_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const speakers_expertise = pgTable(
  "speakers_expertise",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    area: varchar("area"),
  },
  (columns) => [
    index("speakers_expertise_order_idx").on(columns._order),
    index("speakers_expertise_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [speakers.id],
      name: "speakers_expertise_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const speakers = pgTable(
  "speakers",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    title: varchar("title").notNull(),
    organization: varchar("organization").notNull(),
    country: varchar("country").notNull(),
    photo: integer("photo_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    bio: jsonb("bio").notNull(),
    featured: boolean("featured").default(false),
    socialMedia_twitter: varchar("social_media_twitter"),
    socialMedia_linkedin: varchar("social_media_linkedin"),
    socialMedia_website: varchar("social_media_website"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("speakers_photo_idx").on(columns.photo),
    index("speakers_updated_at_idx").on(columns.updatedAt),
    index("speakers_created_at_idx").on(columns.createdAt),
  ],
);

export const speakers_rels = pgTable(
  "speakers_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    sessionsID: integer("sessions_id"),
  },
  (columns) => [
    index("speakers_rels_order_idx").on(columns.order),
    index("speakers_rels_parent_idx").on(columns.parent),
    index("speakers_rels_path_idx").on(columns.path),
    index("speakers_rels_sessions_id_idx").on(columns.sessionsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [speakers.id],
      name: "speakers_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["sessionsID"]],
      foreignColumns: [sessions.id],
      name: "speakers_rels_sessions_fk",
    }).onDelete("cascade"),
  ],
);

export const sessions_materials = pgTable(
  "sessions_materials",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    material: integer("material_id").references(() => media.id, {
      onDelete: "set null",
    }),
    description: varchar("description"),
  },
  (columns) => [
    index("sessions_materials_order_idx").on(columns._order),
    index("sessions_materials_parent_id_idx").on(columns._parentID),
    index("sessions_materials_material_idx").on(columns.material),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [sessions.id],
      name: "sessions_materials_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const sessions = pgTable(
  "sessions",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    description: jsonb("description").notNull(),
    type: enum_sessions_type("type").notNull(),
    track: enum_sessions_track("track"),
    date: timestamp("date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    startTime: timestamp("start_time", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    endTime: timestamp("end_time", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    venue: varchar("venue").notNull(),
    capacity: numeric("capacity", { mode: "number" }),
    moderator: integer("moderator_id").references(() => speakers.id, {
      onDelete: "set null",
    }),
    requiresRegistration: boolean("requires_registration").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("sessions_moderator_idx").on(columns.moderator),
    index("sessions_updated_at_idx").on(columns.updatedAt),
    index("sessions_created_at_idx").on(columns.createdAt),
  ],
);

export const sessions_rels = pgTable(
  "sessions_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    speakersID: integer("speakers_id"),
    abstractsID: integer("abstracts_id"),
  },
  (columns) => [
    index("sessions_rels_order_idx").on(columns.order),
    index("sessions_rels_parent_idx").on(columns.parent),
    index("sessions_rels_path_idx").on(columns.path),
    index("sessions_rels_speakers_id_idx").on(columns.speakersID),
    index("sessions_rels_abstracts_id_idx").on(columns.abstractsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [sessions.id],
      name: "sessions_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["speakersID"]],
      foreignColumns: [speakers.id],
      name: "sessions_rels_speakers_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["abstractsID"]],
      foreignColumns: [abstracts.id],
      name: "sessions_rels_abstracts_fk",
    }).onDelete("cascade"),
  ],
);

export const resources_topics = pgTable(
  "resources_topics",
  {
    order: integer("order").notNull(),
    parent: integer("parent_id").notNull(),
    value: enum_resources_topics("value"),
    id: serial("id").primaryKey(),
  },
  (columns) => [
    index("resources_topics_order_idx").on(columns.order),
    index("resources_topics_parent_idx").on(columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [resources.id],
      name: "resources_topics_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const resources_authors = pgTable(
  "resources_authors",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    author: varchar("author"),
  },
  (columns) => [
    index("resources_authors_order_idx").on(columns._order),
    index("resources_authors_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [resources.id],
      name: "resources_authors_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const resources = pgTable(
  "resources",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    description: varchar("description").notNull(),
    file: integer("file_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    type: enum_resources_type("type").notNull(),
    year: numeric("year", { mode: "number" }).notNull(),
    sarsycEdition: enum_resources_sarsyc_edition("sarsyc_edition"),
    country: varchar("country"),
    language: enum_resources_language("language").default("en"),
    downloads: numeric("downloads", { mode: "number" }).default(0),
    featured: boolean("featured").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("resources_slug_idx").on(columns.slug),
    index("resources_file_idx").on(columns.file),
    index("resources_updated_at_idx").on(columns.updatedAt),
    index("resources_created_at_idx").on(columns.createdAt),
  ],
);

export const news_category = pgTable(
  "news_category",
  {
    order: integer("order").notNull(),
    parent: integer("parent_id").notNull(),
    value: enum_news_category("value"),
    id: serial("id").primaryKey(),
  },
  (columns) => [
    index("news_category_order_idx").on(columns.order),
    index("news_category_parent_idx").on(columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [news.id],
      name: "news_category_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const news_tags = pgTable(
  "news_tags",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    tag: varchar("tag"),
  },
  (columns) => [
    index("news_tags_order_idx").on(columns._order),
    index("news_tags_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [news.id],
      name: "news_tags_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const news = pgTable(
  "news",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    excerpt: varchar("excerpt").notNull(),
    content: jsonb("content").notNull(),
    featuredImage: integer("featured_image_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    author: integer("author_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    status: enum_news_status("status").notNull().default("draft"),
    publishedDate: timestamp("published_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    featured: boolean("featured").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("news_slug_idx").on(columns.slug),
    index("news_featured_image_idx").on(columns.featuredImage),
    index("news_author_idx").on(columns.author),
    index("news_updated_at_idx").on(columns.updatedAt),
    index("news_created_at_idx").on(columns.createdAt),
  ],
);

export const partners_sarsyc_editions = pgTable(
  "partners_sarsyc_editions",
  {
    order: integer("order").notNull(),
    parent: integer("parent_id").notNull(),
    value: enum_partners_sarsyc_editions("value"),
    id: serial("id").primaryKey(),
  },
  (columns) => [
    index("partners_sarsyc_editions_order_idx").on(columns.order),
    index("partners_sarsyc_editions_parent_idx").on(columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [partners.id],
      name: "partners_sarsyc_editions_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const partners = pgTable(
  "partners",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    logo: integer("logo_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    description: jsonb("description"),
    type: enum_partners_type("type").notNull(),
    tier: enum_partners_tier("tier"),
    website: varchar("website"),
    active: boolean("active").default(true),
    displayOrder: numeric("display_order", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("partners_logo_idx").on(columns.logo),
    index("partners_updated_at_idx").on(columns.updatedAt),
    index("partners_created_at_idx").on(columns.createdAt),
  ],
);

export const faqs = pgTable(
  "faqs",
  {
    id: serial("id").primaryKey(),
    question: varchar("question").notNull(),
    answer: jsonb("answer").notNull(),
    category: enum_faqs_category("category").notNull(),
    order: numeric("order", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("faqs_updated_at_idx").on(columns.updatedAt),
    index("faqs_created_at_idx").on(columns.createdAt),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    caption: varchar("caption"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_card_url: varchar("sizes_card_url"),
    sizes_card_width: numeric("sizes_card_width", { mode: "number" }),
    sizes_card_height: numeric("sizes_card_height", { mode: "number" }),
    sizes_card_mimeType: varchar("sizes_card_mime_type"),
    sizes_card_filesize: numeric("sizes_card_filesize", { mode: "number" }),
    sizes_card_filename: varchar("sizes_card_filename"),
    sizes_hero_url: varchar("sizes_hero_url"),
    sizes_hero_width: numeric("sizes_hero_width", { mode: "number" }),
    sizes_hero_height: numeric("sizes_hero_height", { mode: "number" }),
    sizes_hero_mimeType: varchar("sizes_hero_mime_type"),
    sizes_hero_filesize: numeric("sizes_hero_filesize", { mode: "number" }),
    sizes_hero_filename: varchar("sizes_hero_filename"),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
    index("media_sizes_card_sizes_card_filename_idx").on(
      columns.sizes_card_filename,
    ),
    index("media_sizes_hero_sizes_hero_filename_idx").on(
      columns.sizes_hero_filename,
    ),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    registrationsID: integer("registrations_id"),
    abstractsID: integer("abstracts_id"),
    speakersID: integer("speakers_id"),
    sessionsID: integer("sessions_id"),
    resourcesID: integer("resources_id"),
    newsID: integer("news_id"),
    partnersID: integer("partners_id"),
    faqsID: integer("faqs_id"),
    mediaID: integer("media_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_registrations_id_idx").on(
      columns.registrationsID,
    ),
    index("payload_locked_documents_rels_abstracts_id_idx").on(
      columns.abstractsID,
    ),
    index("payload_locked_documents_rels_speakers_id_idx").on(
      columns.speakersID,
    ),
    index("payload_locked_documents_rels_sessions_id_idx").on(
      columns.sessionsID,
    ),
    index("payload_locked_documents_rels_resources_id_idx").on(
      columns.resourcesID,
    ),
    index("payload_locked_documents_rels_news_id_idx").on(columns.newsID),
    index("payload_locked_documents_rels_partners_id_idx").on(
      columns.partnersID,
    ),
    index("payload_locked_documents_rels_faqs_id_idx").on(columns.faqsID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["registrationsID"]],
      foreignColumns: [registrations.id],
      name: "payload_locked_documents_rels_registrations_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["abstractsID"]],
      foreignColumns: [abstracts.id],
      name: "payload_locked_documents_rels_abstracts_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["speakersID"]],
      foreignColumns: [speakers.id],
      name: "payload_locked_documents_rels_speakers_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["sessionsID"]],
      foreignColumns: [sessions.id],
      name: "payload_locked_documents_rels_sessions_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["resourcesID"]],
      foreignColumns: [resources.id],
      name: "payload_locked_documents_rels_resources_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["newsID"]],
      foreignColumns: [news.id],
      name: "payload_locked_documents_rels_news_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["partnersID"]],
      foreignColumns: [partners.id],
      name: "payload_locked_documents_rels_partners_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["faqsID"]],
      foreignColumns: [faqs.id],
      name: "payload_locked_documents_rels_faqs_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const site_settings = pgTable("site_settings", {
  id: serial("id").primaryKey(),
  conferenceName: varchar("conference_name").default("SARSYC VI"),
  conferenceTheme: varchar("conference_theme").default(
    "Align for Action: Sustaining Progress in Youth Health and Education",
  ),
  conferenceDate: timestamp("conference_date", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }).notNull(),
  conferenceEndDate: timestamp("conference_end_date", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }).notNull(),
  conferenceLocation: varchar("conference_location").default(
    "Windhoek, Namibia",
  ),
  conferenceVenue: varchar("conference_venue"),
  registrationOpen: boolean("registration_open").default(false),
  registrationOpenDate: timestamp("registration_open_date", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  earlyBirdDeadline: timestamp("early_bird_deadline", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  registrationCloseDate: timestamp("registration_close_date", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  abstractsOpen: boolean("abstracts_open").default(false),
  abstractDeadline: timestamp("abstract_deadline", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  contactEmail: varchar("contact_email").notNull(),
  contactPhone: varchar("contact_phone"),
  address: varchar("address"),
  facebook: varchar("facebook"),
  twitter: varchar("twitter"),
  instagram: varchar("instagram"),
  linkedin: varchar("linkedin"),
  youtube: varchar("youtube"),
  siteTitle: varchar("site_title").default(
    "SARSYC VI - Southern African Regional Students and Youth Conference",
  ),
  siteDescription: varchar("site_description").default(
    "Join us for SARSYC VI in Windhoek, Namibia. The premier regional platform for youth health and education advocacy.",
  ),
  googleAnalyticsId: varchar("google_analytics_id"),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const header_nav_items_sub_items = pgTable(
  "header_nav_items_sub_items",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    label: varchar("label").notNull(),
    link: varchar("link").notNull(),
  },
  (columns) => [
    index("header_nav_items_sub_items_order_idx").on(columns._order),
    index("header_nav_items_sub_items_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [header_nav_items.id],
      name: "header_nav_items_sub_items_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const header_nav_items = pgTable(
  "header_nav_items",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    label: varchar("label").notNull(),
    link: varchar("link").notNull(),
  },
  (columns) => [
    index("header_nav_items_order_idx").on(columns._order),
    index("header_nav_items_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [header.id],
      name: "header_nav_items_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const header = pgTable(
  "header",
  {
    id: serial("id").primaryKey(),
    logo: integer("logo_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    ctaButton_text: varchar("cta_button_text").default("Register Now"),
    ctaButton_link: varchar("cta_button_link").default("/participate/register"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [index("header_logo_idx").on(columns.logo)],
);

export const footer_columns_links = pgTable(
  "footer_columns_links",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    label: varchar("label").notNull(),
    url: varchar("url").notNull(),
  },
  (columns) => [
    index("footer_columns_links_order_idx").on(columns._order),
    index("footer_columns_links_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [footer_columns.id],
      name: "footer_columns_links_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const footer_columns = pgTable(
  "footer_columns",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    heading: varchar("heading").notNull(),
  },
  (columns) => [
    index("footer_columns_order_idx").on(columns._order),
    index("footer_columns_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [footer.id],
      name: "footer_columns_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const footer = pgTable("footer", {
  id: serial("id").primaryKey(),
  description: varchar("description").default(
    "SARSYC is the premier regional platform for students and youth working on reproductive health advocacy in Southern Africa.",
  ),
  copyright: varchar("copyright").default(
    "© 2026 SAYWHAT. All rights reserved.",
  ),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_registrations_dietary_restrictions = relations(
  registrations_dietary_restrictions,
  ({ one }) => ({
    parent: one(registrations, {
      fields: [registrations_dietary_restrictions.parent],
      references: [registrations.id],
      relationName: "dietaryRestrictions",
    }),
  }),
);
export const relations_registrations = relations(registrations, ({ many }) => ({
  dietaryRestrictions: many(registrations_dietary_restrictions, {
    relationName: "dietaryRestrictions",
  }),
}));
export const relations_abstracts_keywords = relations(
  abstracts_keywords,
  ({ one }) => ({
    _parentID: one(abstracts, {
      fields: [abstracts_keywords._parentID],
      references: [abstracts.id],
      relationName: "keywords",
    }),
  }),
);
export const relations_abstracts_co_authors = relations(
  abstracts_co_authors,
  ({ one }) => ({
    _parentID: one(abstracts, {
      fields: [abstracts_co_authors._parentID],
      references: [abstracts.id],
      relationName: "coAuthors",
    }),
  }),
);
export const relations_abstracts = relations(abstracts, ({ one, many }) => ({
  keywords: many(abstracts_keywords, {
    relationName: "keywords",
  }),
  coAuthors: many(abstracts_co_authors, {
    relationName: "coAuthors",
  }),
  abstractFile: one(media, {
    fields: [abstracts.abstractFile],
    references: [media.id],
    relationName: "abstractFile",
  }),
  assignedSession: one(sessions, {
    fields: [abstracts.assignedSession],
    references: [sessions.id],
    relationName: "assignedSession",
  }),
}));
export const relations_speakers_type = relations(speakers_type, ({ one }) => ({
  parent: one(speakers, {
    fields: [speakers_type.parent],
    references: [speakers.id],
    relationName: "type",
  }),
}));
export const relations_speakers_expertise = relations(
  speakers_expertise,
  ({ one }) => ({
    _parentID: one(speakers, {
      fields: [speakers_expertise._parentID],
      references: [speakers.id],
      relationName: "expertise",
    }),
  }),
);
export const relations_speakers_rels = relations(speakers_rels, ({ one }) => ({
  parent: one(speakers, {
    fields: [speakers_rels.parent],
    references: [speakers.id],
    relationName: "_rels",
  }),
  sessionsID: one(sessions, {
    fields: [speakers_rels.sessionsID],
    references: [sessions.id],
    relationName: "sessions",
  }),
}));
export const relations_speakers = relations(speakers, ({ one, many }) => ({
  photo: one(media, {
    fields: [speakers.photo],
    references: [media.id],
    relationName: "photo",
  }),
  type: many(speakers_type, {
    relationName: "type",
  }),
  expertise: many(speakers_expertise, {
    relationName: "expertise",
  }),
  _rels: many(speakers_rels, {
    relationName: "_rels",
  }),
}));
export const relations_sessions_materials = relations(
  sessions_materials,
  ({ one }) => ({
    _parentID: one(sessions, {
      fields: [sessions_materials._parentID],
      references: [sessions.id],
      relationName: "materials",
    }),
    material: one(media, {
      fields: [sessions_materials.material],
      references: [media.id],
      relationName: "material",
    }),
  }),
);
export const relations_sessions_rels = relations(sessions_rels, ({ one }) => ({
  parent: one(sessions, {
    fields: [sessions_rels.parent],
    references: [sessions.id],
    relationName: "_rels",
  }),
  speakersID: one(speakers, {
    fields: [sessions_rels.speakersID],
    references: [speakers.id],
    relationName: "speakers",
  }),
  abstractsID: one(abstracts, {
    fields: [sessions_rels.abstractsID],
    references: [abstracts.id],
    relationName: "abstracts",
  }),
}));
export const relations_sessions = relations(sessions, ({ one, many }) => ({
  moderator: one(speakers, {
    fields: [sessions.moderator],
    references: [speakers.id],
    relationName: "moderator",
  }),
  materials: many(sessions_materials, {
    relationName: "materials",
  }),
  _rels: many(sessions_rels, {
    relationName: "_rels",
  }),
}));
export const relations_resources_topics = relations(
  resources_topics,
  ({ one }) => ({
    parent: one(resources, {
      fields: [resources_topics.parent],
      references: [resources.id],
      relationName: "topics",
    }),
  }),
);
export const relations_resources_authors = relations(
  resources_authors,
  ({ one }) => ({
    _parentID: one(resources, {
      fields: [resources_authors._parentID],
      references: [resources.id],
      relationName: "authors",
    }),
  }),
);
export const relations_resources = relations(resources, ({ one, many }) => ({
  file: one(media, {
    fields: [resources.file],
    references: [media.id],
    relationName: "file",
  }),
  topics: many(resources_topics, {
    relationName: "topics",
  }),
  authors: many(resources_authors, {
    relationName: "authors",
  }),
}));
export const relations_news_category = relations(news_category, ({ one }) => ({
  parent: one(news, {
    fields: [news_category.parent],
    references: [news.id],
    relationName: "category",
  }),
}));
export const relations_news_tags = relations(news_tags, ({ one }) => ({
  _parentID: one(news, {
    fields: [news_tags._parentID],
    references: [news.id],
    relationName: "tags",
  }),
}));
export const relations_news = relations(news, ({ one, many }) => ({
  featuredImage: one(media, {
    fields: [news.featuredImage],
    references: [media.id],
    relationName: "featuredImage",
  }),
  category: many(news_category, {
    relationName: "category",
  }),
  tags: many(news_tags, {
    relationName: "tags",
  }),
  author: one(users, {
    fields: [news.author],
    references: [users.id],
    relationName: "author",
  }),
}));
export const relations_partners_sarsyc_editions = relations(
  partners_sarsyc_editions,
  ({ one }) => ({
    parent: one(partners, {
      fields: [partners_sarsyc_editions.parent],
      references: [partners.id],
      relationName: "sarsycEditions",
    }),
  }),
);
export const relations_partners = relations(partners, ({ one, many }) => ({
  logo: one(media, {
    fields: [partners.logo],
    references: [media.id],
    relationName: "logo",
  }),
  sarsycEditions: many(partners_sarsyc_editions, {
    relationName: "sarsycEditions",
  }),
}));
export const relations_faqs = relations(faqs, () => ({}));
export const relations_media = relations(media, () => ({}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    registrationsID: one(registrations, {
      fields: [payload_locked_documents_rels.registrationsID],
      references: [registrations.id],
      relationName: "registrations",
    }),
    abstractsID: one(abstracts, {
      fields: [payload_locked_documents_rels.abstractsID],
      references: [abstracts.id],
      relationName: "abstracts",
    }),
    speakersID: one(speakers, {
      fields: [payload_locked_documents_rels.speakersID],
      references: [speakers.id],
      relationName: "speakers",
    }),
    sessionsID: one(sessions, {
      fields: [payload_locked_documents_rels.sessionsID],
      references: [sessions.id],
      relationName: "sessions",
    }),
    resourcesID: one(resources, {
      fields: [payload_locked_documents_rels.resourcesID],
      references: [resources.id],
      relationName: "resources",
    }),
    newsID: one(news, {
      fields: [payload_locked_documents_rels.newsID],
      references: [news.id],
      relationName: "news",
    }),
    partnersID: one(partners, {
      fields: [payload_locked_documents_rels.partnersID],
      references: [partners.id],
      relationName: "partners",
    }),
    faqsID: one(faqs, {
      fields: [payload_locked_documents_rels.faqsID],
      references: [faqs.id],
      relationName: "faqs",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_site_settings = relations(site_settings, () => ({}));
export const relations_header_nav_items_sub_items = relations(
  header_nav_items_sub_items,
  ({ one }) => ({
    _parentID: one(header_nav_items, {
      fields: [header_nav_items_sub_items._parentID],
      references: [header_nav_items.id],
      relationName: "subItems",
    }),
  }),
);
export const relations_header_nav_items = relations(
  header_nav_items,
  ({ one, many }) => ({
    _parentID: one(header, {
      fields: [header_nav_items._parentID],
      references: [header.id],
      relationName: "navItems",
    }),
    subItems: many(header_nav_items_sub_items, {
      relationName: "subItems",
    }),
  }),
);
export const relations_header = relations(header, ({ one, many }) => ({
  logo: one(media, {
    fields: [header.logo],
    references: [media.id],
    relationName: "logo",
  }),
  navItems: many(header_nav_items, {
    relationName: "navItems",
  }),
}));
export const relations_footer_columns_links = relations(
  footer_columns_links,
  ({ one }) => ({
    _parentID: one(footer_columns, {
      fields: [footer_columns_links._parentID],
      references: [footer_columns.id],
      relationName: "links",
    }),
  }),
);
export const relations_footer_columns = relations(
  footer_columns,
  ({ one, many }) => ({
    _parentID: one(footer, {
      fields: [footer_columns._parentID],
      references: [footer.id],
      relationName: "columns",
    }),
    links: many(footer_columns_links, {
      relationName: "links",
    }),
  }),
);
export const relations_footer = relations(footer, ({ many }) => ({
  columns: many(footer_columns, {
    relationName: "columns",
  }),
}));

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role;
  enum_registrations_dietary_restrictions: typeof enum_registrations_dietary_restrictions;
  enum_registrations_category: typeof enum_registrations_category;
  enum_registrations_tshirt_size: typeof enum_registrations_tshirt_size;
  enum_registrations_status: typeof enum_registrations_status;
  enum_registrations_payment_status: typeof enum_registrations_payment_status;
  enum_abstracts_track: typeof enum_abstracts_track;
  enum_abstracts_presentation_type: typeof enum_abstracts_presentation_type;
  enum_abstracts_status: typeof enum_abstracts_status;
  enum_speakers_type: typeof enum_speakers_type;
  enum_sessions_type: typeof enum_sessions_type;
  enum_sessions_track: typeof enum_sessions_track;
  enum_resources_topics: typeof enum_resources_topics;
  enum_resources_type: typeof enum_resources_type;
  enum_resources_sarsyc_edition: typeof enum_resources_sarsyc_edition;
  enum_resources_language: typeof enum_resources_language;
  enum_news_category: typeof enum_news_category;
  enum_news_status: typeof enum_news_status;
  enum_partners_sarsyc_editions: typeof enum_partners_sarsyc_editions;
  enum_partners_type: typeof enum_partners_type;
  enum_partners_tier: typeof enum_partners_tier;
  enum_faqs_category: typeof enum_faqs_category;
  users_sessions: typeof users_sessions;
  users: typeof users;
  registrations_dietary_restrictions: typeof registrations_dietary_restrictions;
  registrations: typeof registrations;
  abstracts_keywords: typeof abstracts_keywords;
  abstracts_co_authors: typeof abstracts_co_authors;
  abstracts: typeof abstracts;
  speakers_type: typeof speakers_type;
  speakers_expertise: typeof speakers_expertise;
  speakers: typeof speakers;
  speakers_rels: typeof speakers_rels;
  sessions_materials: typeof sessions_materials;
  sessions: typeof sessions;
  sessions_rels: typeof sessions_rels;
  resources_topics: typeof resources_topics;
  resources_authors: typeof resources_authors;
  resources: typeof resources;
  news_category: typeof news_category;
  news_tags: typeof news_tags;
  news: typeof news;
  partners_sarsyc_editions: typeof partners_sarsyc_editions;
  partners: typeof partners;
  faqs: typeof faqs;
  media: typeof media;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  site_settings: typeof site_settings;
  header_nav_items_sub_items: typeof header_nav_items_sub_items;
  header_nav_items: typeof header_nav_items;
  header: typeof header;
  footer_columns_links: typeof footer_columns_links;
  footer_columns: typeof footer_columns;
  footer: typeof footer;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_registrations_dietary_restrictions: typeof relations_registrations_dietary_restrictions;
  relations_registrations: typeof relations_registrations;
  relations_abstracts_keywords: typeof relations_abstracts_keywords;
  relations_abstracts_co_authors: typeof relations_abstracts_co_authors;
  relations_abstracts: typeof relations_abstracts;
  relations_speakers_type: typeof relations_speakers_type;
  relations_speakers_expertise: typeof relations_speakers_expertise;
  relations_speakers_rels: typeof relations_speakers_rels;
  relations_speakers: typeof relations_speakers;
  relations_sessions_materials: typeof relations_sessions_materials;
  relations_sessions_rels: typeof relations_sessions_rels;
  relations_sessions: typeof relations_sessions;
  relations_resources_topics: typeof relations_resources_topics;
  relations_resources_authors: typeof relations_resources_authors;
  relations_resources: typeof relations_resources;
  relations_news_category: typeof relations_news_category;
  relations_news_tags: typeof relations_news_tags;
  relations_news: typeof relations_news;
  relations_partners_sarsyc_editions: typeof relations_partners_sarsyc_editions;
  relations_partners: typeof relations_partners;
  relations_faqs: typeof relations_faqs;
  relations_media: typeof relations_media;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_site_settings: typeof relations_site_settings;
  relations_header_nav_items_sub_items: typeof relations_header_nav_items_sub_items;
  relations_header_nav_items: typeof relations_header_nav_items;
  relations_header: typeof relations_header;
  relations_footer_columns_links: typeof relations_footer_columns_links;
  relations_footer_columns: typeof relations_footer_columns;
  relations_footer: typeof relations_footer;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
